#Each new term in the fibonacci sequence is generated by adding the previous 2 terms. So like 1, 2, 3, 5, 8, 13, 21, etc
#By considering the terms in the sequence whose values do not exceed four million, find the sum of the even valued terms

x = 1
y = 2
current = 0 
total = 2 #add 2 because otherwise the method doesn't include the 2 in the beginning hehe

while current < 4000000:
	current = x+y
	if current %2 == 0:
		total += current
	x=y
	y=current

print total

#answer is 4613732