# The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1+2+3+4+5+6+7=28
# First ten terms would be 1,3,6,10,15,21,18,36,45,55
# 28 is the first triangle number to have over five factors. (1,2,4,7,14,28)
# What is the value of the first triangle number to have over 500 factors?
import math
import time

def main():
	start = time.time()
	current = 0
	i = 1
	while find_factors(current) < 500:
		current += i
		i = i+1
	print current
	end = time.time()
	diff = (end - start)*1000
	print "It took %f milliseconds to solve this problem" %diff


def find_factors(num):
	factor_count = 0
	for i in range(1, int(math.sqrt(num)+1)):
		if num % i == 0:
			factor_count = factor_count + 1
	if (math.sqrt(num)+1)/(int(math.sqrt(num))+1) == 0:
		return (factor_count*2-1)
	else:
		return (factor_count*2)
	
main()
#answer is 76576500